import {useEffect,useMemo,useRef,useState} from 'react';
import {Folder,ChevronRight,MousePointer2,CornerDownRight} from 'lucide-react';
import type {Entry,FolderPage,Settings} from '../../shared/types';
import {colors} from '../../shared/categories';
import {layout} from '../treemap';import {bytes} from '../format';
export function Treemap({page,onNavigate,units,onError}:{page:FolderPage;onNavigate:(id:number)=>void;units:Settings['units'];onError:(s:string)=>void}){
 const ref=useRef<HTMLDivElement>(null);const [size,setSize]=useState({w:800,h:420});const [selected,setSelected]=useState<Entry|null>(null);const [hover,setHover]=useState<{entry:Entry;x:number;y:number}|null>(null);
 useEffect(()=>{setSelected(null);setHover(null);},[page.entry.id]);
 useEffect(()=>{const observer=new ResizeObserver(([entry])=>setSize({w:entry.contentRect.width,h:entry.contentRect.height}));if(ref.current)observer.observe(ref.current);return()=>observer.disconnect();},[]);
 const entries=useMemo(()=>new Map(page.children.map(n=>[n.id,n])),[page]);
 const rectangles=useMemo(()=>layout([...page.children,...(page.omittedSize?[{id:-1,size:page.omittedSize}]:[])],size.w,size.h),[page,size]);
 return <section className="panel map-panel"><div className="panel-heading"><div><span className="eyebrow">SPACE DISTRIBUTION</span><h2>Storage map <span className="subtle">/ {page.entry.name}</span></h2></div><span className="hint"><MousePointer2 size={13}/> Double-click a folder to explore</span></div>
 <div className="breadcrumbs">{page.breadcrumbs.map((n,i)=><span key={n.id}>{i>0&&<ChevronRight size={12}/>}<button onClick={()=>onNavigate(n.id)}>{i===0?<><Folder size={13}/> {n.name}</>:n.name}</button></span>)}</div>
 <div className="treemap" ref={ref} onMouseLeave={()=>setHover(null)}>{rectangles.map(r=>{const n=entries.get(r.id);if(!n)return <div key={r.id} className="tile aggregate" style={{left:r.x,top:r.y,width:r.w,height:r.h}}>Other entries<br/>{bytes(page.omittedSize,units)}</div>;const color=n.directory?'#536f9c':colors[n.category];return <button key={n.id} className={`tile ${selected?.id===n.id?'selected':''}`} style={{left:r.x+1,top:r.y+1,width:Math.max(0,r.w-2),height:Math.max(0,r.h-2),background:`linear-gradient(135deg,${color}ee,${color}99)`}} aria-label={`${n.name}, ${bytes(n.size,units)}`} onClick={()=>setSelected(n)} onDoubleClick={()=>n.directory&&onNavigate(n.id)} onKeyDown={e=>{if(e.key==='Enter'&&n.directory)onNavigate(n.id);}} onMouseMove={e=>{const b=ref.current!.getBoundingClientRect();setHover({entry:n,x:Math.min(e.clientX-b.left+12,size.w-280),y:Math.min(e.clientY-b.top+12,size.h-100)});}}>{r.w>65&&r.h>32&&<><strong>{n.directory&&<Folder size={12}/>} {n.name}</strong>{r.h>52&&<span>{bytes(n.size,units)}</span>}{r.h>90&&r.w>110&&<small>{n.directory?'Folder':n.category} · {page.entry.size?(n.size/page.entry.size*100).toFixed(1):0}%</small>}</>}</button>})}
 {!rectangles.length&&<div className="map-empty">This folder contains no files with a nonzero size.</div>}
 {hover&&<div className="map-tooltip" style={{left:Math.max(0,hover.x),top:Math.max(0,hover.y)}}><strong>{hover.entry.name}</strong><span>{hover.entry.path}</span><b>{bytes(hover.entry.size,units)} · {hover.entry.directory?'Folder':hover.entry.extension||'No extension'}</b></div>}</div>
 <div className="map-footer">{selected?<><CornerDownRight size={14}/><span className="truncate">{selected.path}</span><b>{bytes(selected.size,units)}</b>{selected.directory&&<button onClick={()=>onNavigate(selected.id)}>Explore</button>}<button onClick={()=>void window.diskatlas.action(selected.id,'reveal').catch(e=>onError(e.message))}>Reveal</button><button onClick={()=>void window.diskatlas.action(selected.id,'open').catch(e=>onError(e.message))}>Open</button></>:<><span className="status-dot"/> Rectangle area represents logical file size <span className="spacer"/>{countLabel(page.children.length,page.omitted)}</>}</div>
 <div className="legend">{Object.entries(colors).map(([label,color])=><span key={label}><i style={{background:color}}/>{label}</span>)}</div></section>;
}
function countLabel(n:number,omitted:number){return omitted?`${n.toLocaleString()} shown · ${omitted.toLocaleString()} grouped`:`${n.toLocaleString()} entries`;}
